<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Mon, 05 Dec 2011 20:17:25 +0000
 */
$conf['title'] = 'Wiki P.A.I.N.S';
$conf['lang'] = 'fr';
$conf['license'] = 'cc-by-sa';
